=== angelaalobo/LenguajeDeMarcas23-24/Tema 1 Introduccion a LM XML/DTD/ejercicio 5-1.dtd
<!ELEMENT football-league (game+)>
<!ELEMENT game (local-team, visiting-team, goals-local-team, goals-visiting-team)*>
<!ELEMENT local-team (#PCDATA)>
<!ELEMENT visiting-team (#PCDATA)>
<!ELEMENT goals-local-team (#PCDATA)>
<!ELEMENT goals-visiting-team (#PCDATA)>

=== angelaalobo/LenguajeDeMarcas23-24/Tema 1 Introduccion a LM XML/DTD/ejercicio 5-1xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE football-league SYSTEM "ejercicio 5-1.dtd">
<football-league>
    <game>
        <local-team>Nottingham Preesa</local-team>
        <visiting-team>Inter from Mitent</visiting-team>
        <goals-local-team>0</goals-local-team>
        <goals-visiting-team>1</goals-visiting-team>

    </game>
    <game>
        <local-team>Vodka Juniors</local-team>
        <visiting-team>Sparta da Risa</visiting-team>
        <goals-local-team>3</goals-local-team>
        <goals-visiting-team>3</goals-visiting-team>
        
    </game>
    <game>
        <local-team>Water of Munich</local-team>
        <visiting-team>Esteaua is from the tap</visiting-team>
        <goals-local-team>4</goals-local-team>
        <goals-visiting-team>2</goals-visiting-team>
        
    </game>
</football-league>
